// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kXQaMnFtNlE8s-QafgKDAli5zI5sSp0',
    appId: '1:546307604248:web:2fac75b655a21152e1686d',
    messagingSenderId: '546307604248',
    projectId: 'fir-web-app-3c9e1',
    authDomain: 'fir-web-app-3c9e1.firebaseapp.com',
    storageBucket: 'fir-web-app-3c9e1.firebasestorage.app',
    measurementId: 'G-7DJJ4JHXKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXc-0kK0_peP_beV836JsrYEt_oMmBErY',
    appId: '1:546307604248:android:9d10d430925f0a47e1686d',
    messagingSenderId: '546307604248',
    projectId: 'fir-web-app-3c9e1',
    storageBucket: 'fir-web-app-3c9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLaV41qWtzLPCYKNM8xU2E5c7wYtZF2Ek',
    appId: '1:546307604248:ios:151d8d285fcfca5ae1686d',
    messagingSenderId: '546307604248',
    projectId: 'fir-web-app-3c9e1',
    storageBucket: 'fir-web-app-3c9e1.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
